Add build image function to GitHub Actions (#1008)
The 'Build Image' action was primarily written by Holger Friedrich and
then edited for better functionality in the openHABian core repo.

This also contains other changes to the CI setup, such as moving the
ShellCheck checks out of Travis and instead enforcing them in GitHub
Actions.

Along with theses changes, some improvements to the build script and
install output were also made. These changes to the build script include
using cURL over wget for downloading needed files and also cloning the
openHABian repo in the build process rather than the install process.
This change was made because the repo must be present for offline
install to work, and as such it makes sense to provide it with the image
to reduce points of failure on install.

Fixes #991

Co-authored-by: Holger Friedrich <mail@holger-friedrich.de>
Co-authored-by: Markus Storm <markus.storm@gmx.net>
Signed-off-by: Ethan Dye <mrtops03@gmail.com>

diff --git a/.github/workflows/shellcheck-action.yml b/.github/workflows/shellcheck-action.yml
--- a/.github/workflows/shellcheck-action.yml
+++ b/.github/workflows/shellcheck-action.yml
@@ -1,17 +1,22 @@
-# This is a basic workflow to help you get started with Actions
+name: ShellCheck
 
-name: shellcheck
-
-# Controls when the action will run. Triggers the workflow on push or pull request
-# events but only for the master branch
+# Trigger the workflow on push or pull request
 on:
-  push
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
+  push:
+    paths:
+      - '**.bash'
+      - '**.sh'
+      - '!test.bash'
+  pull_request:
+    paths:
+      - '**.bash'
+      - '**.sh'
+      - '!test.bash'
+
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+  shellcheck:
+    # Using latest Ubuntu (not the GitHub Actions default) to get latest tool versions in GitHub Actions environment
+    runs-on: ubuntu-20.04
 
     steps:
        - name: Checkout repository
@@ -20,12 +25,23 @@ jobs:
          run: sudo -E bash -c set
        - name: Install required packages
          run: sudo apt-get install shellcheck
-       - name: "Check 1"
-         run: shellcheck -x -s bash openhabian-setup.sh && echo "shellcheck openhabian-setup.sh - OK";
-       - name: "Check 2"
-         run: shellcheck -x -s bash functions/*.bash && echo "shellcheck functions/*.bash - OK";
-       - name: "Check 3"
-         run: shellcheck -x -s bash build-image/*.bash && echo "shellcheck build-image/*.bash - OK";
-       - name: "Check 4"
-         run: shellcheck -x -s bash build.bash && echo "shellcheck build.bash - OK"
-
+       - name: "ShellCheck openhabian-setup.sh"
+         run: |
+           echo "ShellCheck openhabian-setup.sh..."
+           if shellcheck -x -s bash openhabian-setup.sh; then echo "OK"; else echo "FAILED"; exit 1; fi
+         shell: bash
+       - name: "ShellCheck functions/*.bash"
+         run: |
+           echo "ShellCheck functions/*.bash..."
+           if shellcheck -x -s bash functions/*.bash; then echo "OK"; else echo "FAILED"; exit 1; fi
+         shell: bash
+       - name: "ShellCheck build-image/*.bash"
+         run: |
+           echo "ShellCheck build-image/*.bash..."
+           if shellcheck -x -s bash build-image/*.bash; then echo "OK"; else echo "FAILED"; exit 1; fi
+         shell: bash
+       - name: "ShellCheck build.bash and ci-setup.bash"
+         run: |
+           echo "ShellCheck build.bash..."
+           if shellcheck -x -s bash build.bash ci-setup.bash; then echo "OK"; else echo "FAILED"; exit 1; fi
+         shell: bash
